mqtt:
  host: 'mqtt.my-domain.com'
  port: 1883
  user: 'mqtt'
  password: '123456789'
  topic: 'wateringsystem/sensors'
mysql:
  host: 'localhost'
  database: 'wateringsystem'
  user: 'wateringsystem'
  password: '123456789'