mqtt:
  host: 'mqtt.my-domain.com'
  port: 1883
  user: 'mqtt'
  password: '123456789'
  topics:
    generic: 'wateringsystem/#'
    sensors: 'wateringsystem/sensors'
mysql:
  host: 'localhost'
  database: 'wateringsystem'
  user: 'wateringsystem'
  password: '123456789'
watering:
    minSoilMoisture: 800
    wateringMilliseconds: 1200
    topic: 'wateringsystem/watering'