mqtt:
  host: 'mqtt.my-domain.com'
  port: 1883
  user: 'mqtt'
  password: '123456789'
  topics:
    generic: 'wateringsystem/#'
    sensors: 'wateringsystem/sensors'
    watering: 'wateringsystem/watering'
mysql:
  host: 'localhost'
  database: 'wateringsystem'
  user: 'wateringsystem'
  password: '123456789'
watering:
  minSoilMoisture: 900
  wateringMilliseconds: 15000